#ifndef ERROR_H
#define ERROR_H

enum {
    OK = 0,
    ERROR_CANNOT_CREATE_SOCKET = -1,
    ERROR_CANNOT_BIND_PORT,
    ERROR_LISTEN,
    ERROR_ACCEPT_CONNECTION,
    ERROR_OPENSSL_CREATE_CTX,
    ERROR_OPENSSL_SET_CERT,
    ERROR_OPENSSL_SET_PRIVATEKEY,
    ERROR_OPENSSL_NEW_CONNECTION,
    ERROR_OPENSSL_ACCEPT_CONNECTION,
    ERROR_CANNOT_RESOLVE_HOSTNAME,
    ERROR_CANNOT_CONNECT_SERVER
} RETURN_CODE;

#endif